<?php
error_reporting(0); // Отключаем ошибки, чтобы не ломать программу
ini_set('display_errors', 0);

// Получаем ВСЕ данные, которые шлет программа
$status  = $_POST["status"] ?? "N/A";
$model   = $_POST["model"] ?? "N/A";
$serial  = $_POST["serial"] ?? "N/A";
$imei    = $_POST["imei"] ?? "N/A";
$type    = $_POST["type"] ?? "N/A";
$ios     = $_POST["ios"] ?? "N/A";    
$region  = $_POST["region"] ?? "N/A";
$build   = $_POST["build"] ?? "N/A";   

$botToken = "ВАШ_ТОКЕН"; 
$chatId = "";

$iosFull = "$ios ($build)";

// Формируем красивый и полный текст сообщения
$message = "🔔 NEW DEVICE REPORT\n\n".
"Status: $status\n".
"Model: $model\n".
"Serial: $serial\n".
"IMEI: $imei\n".
"Type: $type\n".
"iOS: $iosFull\n".
"Region: $region\n\n".
"Generated by BobikA5";

// Отправка в Telegram
$url = "https://api.telegram.org/bot$botToken/sendMessage?chat_id=$chatId&text=" . urlencode($message);
@file_get_contents($url);

// ЭТО САМОЕ ВАЖНОЕ:
// Программа в Form1.cs ищет слово "ok" в ответе.
// Если этого не будет, она выдаст "Value cannot be null".
ob_clean();
header('Content-Type: text/plain');
echo "ok"; 
exit();